apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:uS33ofWp8LhgXD/2pLqWFin+z7yhO7umRyq7+mUwyTB93+Z+Ps/lrw==,iv:SGf6Iu0Yv+lEO38LzHpfl3F2brm7sym72FJIqy5DvqU=,tag:HcpDkYA2tnACYKP5YVtgDw==,type:str]
sops:
    age:
        - recipient: age1g5a0avn7nn3p0zaae5pa2udcnhtxscqxt6p7h2mhvluxe4z7pv8q6gaka0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByNXpSQlVpT1R6U1lodnR0
            Z2tYV25FZFI4bjVTM0hyb2MxaStkZkVRN2d3CkRuOG96Z0F6c204RDdtNVgwdmhM
            Sms3b3Z3Sjd4UHVnK0FmbCt2WFNrQlEKLS0tIDY4WVpiWVQ0MDRYbnNHNEV4MjZi
            L0tsL2hQQ0hTUkxXdy83SWNFc0JYZGsKJV5aVdPv9coQpl6oinPP42j1ncgPB8s5
            onME1PgTUQVAwO2fnOAQS1xroPpZxyYBFlSyElvFUWJkAs71HLhB5w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-08T19:37:30Z"
    mac: ENC[AES256_GCM,data:oiXAzaXw/VIig/Lygcvo71DCFa4LRjEWCZSkY/Rs61MljgwAJREWeUh2iazRWHeobzWd49hQq9NsfmFR33nTNVE5J4nRhcJOWKjAx6yDeQttWDqnl6SHbn2lrAWD1jZBTxXKpW861X2b7d7qLPZj/qgC2UIqLEAPnXoZxiyomqw=,iv:CwSpHiMP7F7+XL+h2z1orjxDS6mrluQZrgB1CWWW3ag=,tag:n4U/4uMd1WzOYtNkkcgXDw==,type:str]
    encrypted_regex: ^stringData$
    version: 3.11.0
